"""
pybind11 bindings for egret
"""
from __future__ import annotations
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['BaseArray', 'Coordinate', 'CoordinateArray', 'Dipole', 'Dispersion', 'DispersionArray', 'Drift', 'Element', 'Envelope', 'EnvelopeArray', 'Lattice', 'NonlinearMultipole', 'Object', 'Octupole', 'Quadrupole', 'Ring', 'Sextupole', 'Steering']
class BaseArray:
    def __init__(self, s_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    def __len__(self) -> int:
        ...
    def append(self, other: BaseArray) -> None:
        ...
    def ds(self) -> float:
        ...
    def index_from_s(self, s: typing.SupportsFloat) -> int:
        ...
    def size(self) -> int:
        ...
    @property
    def s_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @s_array.setter
    def s_array(self, arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
class Coordinate:
    def __init__(self, vector: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 1]"] = ..., s: typing.SupportsFloat = 0.0, z: typing.SupportsFloat = 0.0, delta: typing.SupportsFloat = 0.0) -> None:
        ...
    @property
    def delta(self) -> float:
        ...
    @delta.setter
    def delta(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def s(self) -> float:
        ...
    @s.setter
    def s(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def vector(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 1]"]:
        ...
    @vector.setter
    def vector(self, arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 1]"]) -> None:
        ...
    @property
    def x(self) -> float:
        ...
    @x.setter
    def x(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def xp(self) -> float:
        ...
    @xp.setter
    def xp(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def y(self) -> float:
        ...
    @y.setter
    def y(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def yp(self) -> float:
        ...
    @yp.setter
    def yp(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def z(self) -> float:
        ...
    @z.setter
    def z(self, arg1: typing.SupportsFloat) -> None:
        ...
class CoordinateArray(BaseArray):
    def __init__(self, vector_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, n]"], s_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], z_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"] = ..., delta_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"] = ...) -> None:
        ...
    def append(self, other: CoordinateArray) -> None:
        ...
    def from_s(self, s: typing.SupportsFloat) -> Coordinate:
        ...
    @property
    def delta_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @delta_array.setter
    def delta_array(self, arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    @property
    def vector_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, n]"]:
        ...
    @vector_array.setter
    def vector_array(self, arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, n]"]) -> None:
        ...
    @property
    def x_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @x_array.setter
    def x_array(self, arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    @property
    def xp_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @xp_array.setter
    def xp_array(self, arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    @property
    def y_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @y_array.setter
    def y_array(self, arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    @property
    def yp_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @yp_array.setter
    def yp_array(self, arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    @property
    def z_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @z_array.setter
    def z_array(self, arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
class Dipole(Element, Object):
    def __init__(self, name: str, length: typing.SupportsFloat, angle: typing.SupportsFloat, k1: typing.SupportsFloat = 0.0, e1: typing.SupportsFloat = 0.0, e2: typing.SupportsFloat = 0.0, h1: typing.SupportsFloat = 0.0, h2: typing.SupportsFloat = 0.0, dx: typing.SupportsFloat = 0.0, dy: typing.SupportsFloat = 0.0, ds: typing.SupportsFloat = 0.0, tilt: typing.SupportsFloat = 0.0, info: str = '') -> None:
        ...
    @property
    def e1(self) -> float:
        ...
    @e1.setter
    def e1(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def e2(self) -> float:
        ...
    @e2.setter
    def e2(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def h1(self) -> float:
        ...
    @h1.setter
    def h1(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def h2(self) -> float:
        ...
    @h2.setter
    def h2(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def k1(self) -> float:
        ...
    @k1.setter
    def k1(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def rho(self) -> float:
        ...
class Dispersion:
    def __init__(self, vector: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 1]"] = ..., s: typing.SupportsFloat = 0.0) -> None:
        ...
    @property
    def s(self) -> float:
        ...
    @s.setter
    def s(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def vector(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 1]"]:
        ...
    @vector.setter
    def vector(self, arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 1]"]) -> None:
        ...
    @property
    def x(self) -> float:
        ...
    @x.setter
    def x(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def xp(self) -> float:
        ...
    @xp.setter
    def xp(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def y(self) -> float:
        ...
    @y.setter
    def y(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def yp(self) -> float:
        ...
    @yp.setter
    def yp(self, arg1: typing.SupportsFloat) -> None:
        ...
class DispersionArray(BaseArray):
    def __init__(self, vector_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, n]"], s_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    def append(self, other: DispersionArray) -> None:
        ...
    def from_s(self, s: typing.SupportsFloat) -> Dispersion:
        ...
    @property
    def vector_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, n]"]:
        ...
    @vector_array.setter
    def vector_array(self, arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, n]"]) -> None:
        ...
    @property
    def x_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @x_array.setter
    def x_array(self, arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    @property
    def xp_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @xp_array.setter
    def xp_array(self, arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    @property
    def y_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @y_array.setter
    def y_array(self, arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
    @property
    def yp_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @yp_array.setter
    def yp_array(self, arg1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
        ...
class Drift(Element, Object):
    @staticmethod
    def transfer_matrix_array_from_length(length: typing.SupportsFloat, ds: typing.SupportsFloat = 0.1, endpoint: bool = False) -> tuple[list[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]]:
        ...
    @staticmethod
    def transfer_matrix_from_length(length: typing.SupportsFloat) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]:
        ...
    def __init__(self, name: str, length: typing.SupportsFloat, dx: typing.SupportsFloat = 0.0, dy: typing.SupportsFloat = 0.0, ds: typing.SupportsFloat = 0.0, tilt: typing.SupportsFloat = 0.0, info: str = '') -> None:
        ...
class Element(Object):
    info: str
    def __init__(self, name: str, length: typing.SupportsFloat, angle: typing.SupportsFloat = 0.0, dx: typing.SupportsFloat = 0.0, dy: typing.SupportsFloat = 0.0, ds: typing.SupportsFloat = 0.0, tilt: typing.SupportsFloat = 0.0, info: str = '') -> None:
        ...
    def dispersion(self, cood0: egret.cppegret.Coordinate | None = None, ds: typing.SupportsFloat = 0.1) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 1]"]:
        ...
    def dispersion_array(self, cood0: egret.cppegret.Coordinate | None = None, ds: typing.SupportsFloat = 0.1, endpoint: bool = False) -> tuple[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, n]"], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]]:
        ...
    def find_index(self, names: collections.abc.Sequence[str]) -> list[list[int]]:
        ...
    def get_element(self, indices: collections.abc.Sequence[typing.SupportsInt]) -> Element:
        ...
    def get_element_from_s(self, s: typing.SupportsFloat) -> tuple[Element, float]:
        ...
    def get_s(self, indices: collections.abc.Sequence[typing.SupportsInt]) -> float:
        ...
    def radiation_integrals(self, cood0: Coordinate, evlp0: Envelope, disp0: Dispersion, ds: typing.SupportsFloat = 0.1) -> tuple[float, float, float, float, float, float]:
        ...
    def s_array(self, ds: typing.SupportsFloat = 0.1, endpoint: bool = True) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    def set_indices(self, indices: collections.abc.Sequence[typing.SupportsInt] = []) -> None:
        ...
    def transfer(self, cood0: Coordinate, evlp0: egret.cppegret.Envelope | None = None, disp0: egret.cppegret.Dispersion | None = None, ds: typing.SupportsFloat = 0.1) -> tuple[Coordinate, egret.cppegret.Envelope | None, egret.cppegret.Dispersion | None]:
        ...
    def transfer_array(self, cood0: Coordinate, evlp0: egret.cppegret.Envelope | None = None, disp0: egret.cppegret.Dispersion | None = None, ds: typing.SupportsFloat = 0.1, endpoint: bool = False) -> tuple[CoordinateArray, egret.cppegret.EnvelopeArray | None, egret.cppegret.DispersionArray | None]:
        ...
    def transfer_matrix(self, cood0: egret.cppegret.Coordinate | None = None, ds: typing.SupportsFloat = 0.1) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]:
        ...
    def transfer_matrix_array(self, cood0: egret.cppegret.Coordinate | None = None, ds: typing.SupportsFloat = 0.1, endpoint: bool = False) -> tuple[list[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]]:
        ...
    def transfer_matrix_from_s(self, s0: typing.SupportsFloat, cood0: Coordinate, ds: typing.SupportsFloat = 0.1) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]:
        ...
    @property
    def angle(self) -> float:
        ...
    @angle.setter
    def angle(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def ds(self) -> float:
        ...
    @ds.setter
    def ds(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def dx(self) -> float:
        ...
    @dx.setter
    def dx(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def dy(self) -> float:
        ...
    @dy.setter
    def dy(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def elements(self) -> list[Element] | None:
        ...
    @property
    def length(self) -> float:
        ...
    @length.setter
    def length(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def tilt(self) -> float:
        ...
    @tilt.setter
    def tilt(self, arg1: typing.SupportsFloat) -> None:
        ...
class Envelope:
    @staticmethod
    def adjoint(M: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 2]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 2]"]:
        ...
    def __init__(self, cov: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 4]"] = ..., s: typing.SupportsFloat = 0.0, T: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 2]"] | None = None) -> None:
        ...
    def calc_eigenmode(self, T: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 2]"] | None = None) -> None:
        ...
    def transfer(self, M: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 4]"], length: typing.SupportsFloat) -> None:
        ...
    @property
    def T(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 2]"]:
        ...
    @property
    def T_matrix(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]:
        ...
    @property
    def U(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 2]"]:
        ...
    @property
    def V(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 2]"]:
        ...
    @property
    def au(self) -> float:
        ...
    @property
    def av(self) -> float:
        ...
    @property
    def ax(self) -> float:
        ...
    @property
    def ay(self) -> float:
        ...
    @property
    def bu(self) -> float:
        ...
    @property
    def bv(self) -> float:
        ...
    @property
    def bx(self) -> float:
        ...
    @property
    def by(self) -> float:
        ...
    @property
    def cov(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]:
        ...
    @property
    def gu(self) -> float:
        ...
    @property
    def gv(self) -> float:
        ...
    @property
    def gx(self) -> float:
        ...
    @property
    def gy(self) -> float:
        ...
    @property
    def s(self) -> float:
        ...
    @property
    def tau(self) -> float:
        ...
class EnvelopeArray(BaseArray):
    def T(self, index: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 2]"]:
        ...
    def T_matrix(self, index: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]:
        ...
    def U(self, index: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 2]"]:
        ...
    def V(self, index: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 2]"]:
        ...
    def __init__(self, cov_array: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 4]"]], s_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"], T_array: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 2]"]] | None = None) -> None:
        ...
    def append(self, other: EnvelopeArray) -> None:
        ...
    def au(self, index: typing.SupportsInt) -> float:
        ...
    def av(self, index: typing.SupportsInt) -> float:
        ...
    def ax(self, index: typing.SupportsInt) -> float:
        ...
    def ay(self, index: typing.SupportsInt) -> float:
        ...
    def bu(self, index: typing.SupportsInt) -> float:
        ...
    def bv(self, index: typing.SupportsInt) -> float:
        ...
    def bx(self, index: typing.SupportsInt) -> float:
        ...
    def by(self, index: typing.SupportsInt) -> float:
        ...
    def cov(self, index: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]:
        ...
    def from_s(self, s: typing.SupportsFloat) -> Envelope:
        ...
    def gu(self, index: typing.SupportsInt) -> float:
        ...
    def gv(self, index: typing.SupportsInt) -> float:
        ...
    def gx(self, index: typing.SupportsInt) -> float:
        ...
    def gy(self, index: typing.SupportsInt) -> float:
        ...
    def tau(self, index: typing.SupportsInt) -> float:
        ...
    def transport(self: Envelope, M_array: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 4]"]], s_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> EnvelopeArray:
        ...
    @property
    def T_array(self) -> list[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 2]"]]:
        ...
    @property
    def U_array(self) -> list[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 2]"]]:
        ...
    @property
    def V_array(self) -> list[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 2]"]]:
        ...
    @property
    def au_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def av_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def ax_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def ay_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def bu_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def bv_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def bx_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def by_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def cov_array(self) -> list[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]]:
        ...
    @property
    def gu_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def gv_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def gx_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def gy_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
    @property
    def tau_array(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
        ...
class Lattice(Element, Object):
    @staticmethod
    def angle_of(elements: collections.abc.Sequence[Element]) -> float:
        ...
    @staticmethod
    def length_of(elements: collections.abc.Sequence[Element]) -> float:
        ...
    def __init__(self, name: str, elements: collections.abc.Sequence[Element], dx: typing.SupportsFloat = 0.0, dy: typing.SupportsFloat = 0.0, ds: typing.SupportsFloat = 0.0, tilt: typing.SupportsFloat = 0.0, info: str = '') -> None:
        ...
class NonlinearMultipole(Element, Object):
    def __init__(self, name: str, length: typing.SupportsFloat, kick_x: typing.SupportsFloat = 0.0, kick_y: typing.SupportsFloat = 0.0, dx: typing.SupportsFloat = 0.0, dy: typing.SupportsFloat = 0.0, ds: typing.SupportsFloat = 0.0, tilt: typing.SupportsFloat = 0.0, info: str = '') -> None:
        ...
    def get_k(self, cood: Coordinate) -> tuple[complex, complex]:
        ...
    def set_steering(self, kick_x: typing.SupportsFloat | None, kick_y: typing.SupportsFloat | None) -> None:
        ...
    @property
    def k0x(self) -> float:
        ...
    @k0x.setter
    def k0x(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def k0y(self) -> float:
        ...
    @k0y.setter
    def k0y(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def kick_x(self) -> float:
        ...
    @kick_x.setter
    def kick_x(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def kick_y(self) -> float:
        ...
    @kick_y.setter
    def kick_y(self, arg1: typing.SupportsFloat) -> None:
        ...
class Object:
    name: str
    def __init__(self, name: str) -> None:
        ...
class Octupole(NonlinearMultipole, Element, Object):
    def __init__(self, name: str, length: typing.SupportsFloat, k3: typing.SupportsFloat, k1: typing.SupportsFloat = 0.0, tilt_quad: typing.SupportsFloat = 0.0, kick_x: typing.SupportsFloat = 0.0, kick_y: typing.SupportsFloat = 0.0, dx: typing.SupportsFloat = 0.0, dy: typing.SupportsFloat = 0.0, ds: typing.SupportsFloat = 0.0, tilt: typing.SupportsFloat = 0.0, info: str = '') -> None:
        ...
    def set_quadrupole(self, k1: typing.SupportsFloat | None = None, tilt_quad: typing.SupportsFloat | None = None) -> None:
        ...
    @property
    def k1(self) -> float:
        ...
    @k1.setter
    def k1(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def k3(self) -> float:
        ...
    @k3.setter
    def k3(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def tilt_quad(self) -> float:
        ...
    @tilt_quad.setter
    def tilt_quad(self, arg1: typing.SupportsFloat) -> None:
        ...
class Quadrupole(Element, Object):
    @staticmethod
    def rotation_matrix(tilt: typing.SupportsFloat) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]:
        ...
    @staticmethod
    def transfer_by_length_k1(cood0_vec: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 1]"], length: typing.SupportsFloat, k1: typing.SupportsFloat, k0x: typing.SupportsFloat, k0y: typing.SupportsFloat, tilt: typing.SupportsFloat, tmat_flag: bool = False, disp_flag: bool = False) -> tuple[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"] | None, typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 1]"] | None]:
        ...
    @staticmethod
    def transfer_matrix_from_length_k1(length: typing.SupportsFloat, k1: typing.SupportsFloat, rmat: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[4, 4]"] | None = None) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[4, 4]"]:
        ...
    def __init__(self, name: str, length: typing.SupportsFloat, k1: typing.SupportsFloat, dx: typing.SupportsFloat = 0.0, dy: typing.SupportsFloat = 0.0, ds: typing.SupportsFloat = 0.0, tilt: typing.SupportsFloat = 0.0, info: str = '') -> None:
        ...
    @property
    def k1(self) -> float:
        ...
    @k1.setter
    def k1(self, arg1: typing.SupportsFloat) -> None:
        ...
class Ring(Element, Object):
    C_q: typing.ClassVar[float] = 3.83193864e-13
    m_e_eV: typing.ClassVar[float] = 510998.95
    max_iter_cod: typing.ClassVar[int] = 100
    tol_cod: typing.ClassVar[float] = 1e-07
    def __init__(self, name: str, elements: collections.abc.Sequence[Element], energy: typing.SupportsFloat, info: str = '') -> None:
        ...
    def find_initial_coordinate_of_closed_orbit(self, cood_guess: Coordinate = None) -> Coordinate:
        ...
    def update(self, delta: typing.SupportsFloat = 0.0) -> None:
        ...
    @property
    def J_x(self) -> float:
        ...
    @property
    def J_y(self) -> float:
        ...
    @property
    def J_z(self) -> float:
        ...
    @property
    def cood0(self) -> Coordinate:
        ...
    @property
    def disp0(self) -> Dispersion:
        ...
    @property
    def emittance_x(self) -> float:
        ...
    @property
    def emittance_y(self) -> float:
        ...
    @property
    def energy(self) -> float:
        ...
    @property
    def evlp0(self) -> Envelope:
        ...
    @property
    def tune_x(self) -> float:
        ...
    @property
    def tune_y(self) -> float:
        ...
class Sextupole(NonlinearMultipole, Element, Object):
    def __init__(self, name: str, length: typing.SupportsFloat, k2: typing.SupportsFloat, kick_x: typing.SupportsFloat = 0.0, kick_y: typing.SupportsFloat = 0.0, dx: typing.SupportsFloat = 0.0, dy: typing.SupportsFloat = 0.0, ds: typing.SupportsFloat = 0.0, tilt: typing.SupportsFloat = 0.0, info: str = '') -> None:
        ...
    @property
    def k2(self) -> float:
        ...
    @k2.setter
    def k2(self, arg1: typing.SupportsFloat) -> None:
        ...
class Steering(Element, Object):
    def __init__(self, name: str, length: typing.SupportsFloat, kick_x: typing.SupportsFloat = 0.0, kick_y: typing.SupportsFloat = 0.0, dx: typing.SupportsFloat = 0.0, dy: typing.SupportsFloat = 0.0, ds: typing.SupportsFloat = 0.0, tilt: typing.SupportsFloat = 0.0, info: str = '') -> None:
        ...
    def set_steering(self, kick_x: typing.SupportsFloat | None, kick_y: typing.SupportsFloat | None) -> None:
        ...
    @property
    def kick(self) -> tuple[float, float]:
        ...
    @kick.setter
    def kick(self, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> None:
        ...
    @property
    def kick_x(self) -> float:
        ...
    @kick_x.setter
    def kick_x(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def kick_y(self) -> float:
        ...
    @kick_y.setter
    def kick_y(self, arg1: typing.SupportsFloat) -> None:
        ...
